### PR TITLE
Rule8715

### PR DESCRIPTION
**Pull request by GBurrel**

### CODE REVIEW

**Review by GBurrel — COMMENTED** [review]
Issue with the formatting of the dates within the code.

**Comment by tab1tha** [comment]
You've come quite close @GBurrel . This is a good first step !. 
You created appropriate test cases in your test validate function.  We will have to tweak a few things about the logic in the validate function.
What works best for you? Should I make the changes and write comments explaining what I did or should we meet up and code through together?. I am happy either way.

**Comment by GBurrel** [comment]
Hi @tab1tha,

Thank you for the feedback. Would you be able to make the changes and provide the comments please.

**Comment by tab1tha** [comment]
Sure !

**Review by tab1tha — APPROVED** [review]
Hi @GBurrel 

It's a brave thing to take the first step into coding.
As I said earlier, I could see from your code that you had an idea of what you wanted to do. 
This is an implementation with as many notes as I could put in.

The other issue which you did is quite similar to this. I appreciate that a number of things that are spelt out here were not totally obvious in the documentation. Do you want to give your other issue a second try?
I am also happy to go through that with you. I have the time.

First,
Welcome to the team @GBurrel  !

**Pull request merged**
